"""initial migration - all models

Revision ID: 00ced887fa46
Revises: 
Create Date: 2026-04-13 12:51:26.873561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ced887fa46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cor', sa.String(length=20), nullable=True),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('plano', sa.String(length=30), nullable=True),
    sa.Column('max_usuarios', sa.Integer(), nullable=True),
    sa.Column('max_obras', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('trial_ativo', sa.Boolean(), nullable=True),
    sa.Column('trial_expira', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('config_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=100), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=100), nullable=True),
    sa.Column('smtp_password', sa.String(length=256), nullable=True),
    sa.Column('smtp_usar_tls', sa.Boolean(), nullable=True),
    sa.Column('email_destino', sa.String(length=200), nullable=True),
    sa.Column('alertas_ativos', sa.Boolean(), nullable=True),
    sa.Column('ultimo_envio', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_table('contas_bancarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('agencia', sa.String(length=20), nullable=True),
    sa.Column('conta', sa.String(length=30), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('saldo_inicial', sa.Float(), nullable=True),
    sa.Column('saldo_atual', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('telefone_2', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('contato', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('orcamento_previsto', sa.Float(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim_prevista', sa.Date(), nullable=True),
    sa.Column('data_fim_real', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progresso', sa.Integer(), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('cliente', sa.String(length=200), nullable=True),
    sa.Column('imagem', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=200), nullable=False),
    sa.Column('cliente_email', sa.String(length=120), nullable=True),
    sa.Column('cliente_telefone', sa.String(length=20), nullable=True),
    sa.Column('cliente_endereco', sa.String(length=300), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('valor_materiais', sa.Float(), nullable=True),
    sa.Column('valor_mao_obra', sa.Float(), nullable=True),
    sa.Column('valor_equipamentos', sa.Float(), nullable=True),
    sa.Column('valor_outros', sa.Float(), nullable=True),
    sa.Column('desconto', sa.Float(), nullable=True),
    sa.Column('prazo_execucao', sa.Integer(), nullable=True),
    sa.Column('validade', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=200), nullable=True),
    sa.Column('enviado', sa.Boolean(), nullable=True),
    sa.Column('data_envio', sa.Date(), nullable=True),
    sa.Column('visualizado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('cargo', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'email', name='unique_email_empresa'),
    sa.UniqueConstraint('empresa_id', 'username', name='unique_username_empresa')
    )
    op.create_table('compras_fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('cliente', sa.String(length=200), nullable=False),
    sa.Column('cliente_cnpj', sa.String(length=20), nullable=True),
    sa.Column('cliente_email', sa.String(length=120), nullable=True),
    sa.Column('cliente_telefone', sa.String(length=20), nullable=True),
    sa.Column('cliente_endereco', sa.String(length=300), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('valor_aditivo', sa.Float(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('data_assinatura', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('arquivo', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lancamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('status_pagamento', sa.String(length=20), nullable=True),
    sa.Column('parcelas', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('documento', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lancamentos_conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('documento', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas_bancarias.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs_atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('entidade', sa.String(length=50), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('lancamento_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('enviada_email', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcelas_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcelas_contrato')
    op.drop_table('notificacoes')
    op.drop_table('logs_atividade')
    op.drop_table('lancamentos_conta')
    op.drop_table('lancamentos')
    op.drop_table('itens_orcamento')
    op.drop_table('contratos')
    op.drop_table('compras_fornecedor')
    op.drop_table('usuarios')
    op.drop_table('orcamentos')
    op.drop_table('obras')
    op.drop_table('fornecedores')
    op.drop_table('contas_bancarias')
    op.drop_table('config_email')
    op.drop_table('empresas')
    op.drop_table('categorias')
    # ### end Alembic commands ###
