"""add config_ia table

Revision ID: add_config_ia_002
Revises: soft_delete_001
Create Date: 2026-04-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_config_ia_002'
down_revision = 'soft_delete_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('openai_api_key', sa.String(length=500), nullable=True),
    sa.Column('openai_model', sa.String(length=50), nullable=True),
    sa.Column('gemini_api_key', sa.String(length=500), nullable=True),
    sa.Column('claude_api_key', sa.String(length=500), nullable=True),
    sa.Column('ia_padrao', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    with op.batch_alter_table('config_ia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_ia_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_ia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_ia_empresa_id'))

    op.drop_table('config_ia')
    # ### end Alembic commands ###
