"""add 2FA support to users

Revision ID: d838bedcd1a5
Revises: 00ced887fa46
Create Date: 2026-04-13 13:13:09.872117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd838bedcd1a5'
down_revision = '00ced887fa46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('backup_codes', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('uq_usuarios_totp_secret', ['totp_secret'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('uq_usuarios_totp_secret', type_='unique')
        batch_op.drop_column('backup_codes')
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
